x=input("Enter a commc seperated list values: ").split(",")
color=list(x)
print("The first color is %s and the last color is %s"%(color[0],color[-1]))x=input("Enter a commc seperated list values: ").split(",")
color=list(x)
print("The first color is %s and the last color is %s"%(color[0],color[-1]))
